### ISSUE TITLE
Posted blog does not appear on site

### ISSUE THREAD

**Issue by andrew-boyd** [AtticusRoberts/blog#2]
not sure how far along you are with this functionality, but when I create and account and then post a blog I'm allowed to submit the form but nothing then gets appended to the homepage. There is also no indication given that something has gone wrong.

**Comment by AtticusRoberts** [comment]
I think it's an error with mysql not working properly in the background when I log out of the server. Laravel is able to get data from mysql when I'm not in the server, but it doesn't appear to be able to post to mysql. I'll look into the issue.

**Comment by AtticusRoberts** [comment]
I edited the .env file so it points to the database at 192.241.130.222 instead of 127.0.0.1, and that seemed to fix it.

**Comment by AtticusRoberts** [comment]
I edited the .env file to point to the server instead of the server's localhost, and changed the way I called the insert statement. As far as I can tell both issues should be fixed now. Let me know if you find anything else.

**Comment by andrew-boyd** [comment]
Looks to be fixed for me after creating a new account. Good job!
